name: release jank win

on:
  push:

jobs:

  windows-build-clang:
    name: Windows MSYS2 - clang
    runs-on: windows-2022
    timeout-minutes: 200
    outputs:
      jank-win-commit: ${{ steps.get-jank-commit.outputs.jank_win_commit }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout the release repo
        run: |
          git clone https://github.com/ikappaki/jank-win.git jank-win

      - name: Record jank-win commit
        id: get-jank-commit
        run: |
          cd jank-win
          echo "jank_win_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Cache Clang/LLVM
        id: clang-cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: |
            ${{ github.workspace }}/jank-win/compiler+runtime/build/llvm-install
          key: clang-${{ runner.os }}-${{ hashFiles('jank-win/compiler+runtime/bin/build-clang', 'jank-win/compiler+runtime/third-party/MINGW-packages/mingw-w64-llvm/**') }}

      - uses: msys2/setup-msys2@v2
        if: steps.clang-cache.outputs.cache-hit != 'true'
        with:
          msystem: CLANG64
          install: base-devel git mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-ninja mingw-w64-clang-x86_64-pkgconf mingw-w64-clang-x86_64-libunwind mingw-w64-clang-x86_64-libffi mingw-w64-clang-x86_64-z3 mingw-w64-clang-x86_64-python mingw-w64-clang-x86_64-compiler-rt mingw-w64-clang-x86_64-libc++
          update: true

      - name: Build Clang/LLVM
        if: steps.clang-cache.outputs.cache-hit != 'true'
        shell: msys2 {0}
        env:
          MSYSTEM: CLANG64
        run: |
          pushd jank-win/compiler+runtime
            ./bin/build-clang
          popd

      - name: Verify cached Clang
        env:
          MSYSTEM: CLANG64
        run: dir jank-win/compiler+runtime/build/llvm-install

      # - name: Upload LLVM/Clang build as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: clang64-build
      #     path: jank-win/compiler+runtime/build/llvm-install

  build:
    needs:
      windows-build-clang

    # if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/master'}}
    strategy:
      fail-fast: false
      matrix:
        include: [
          # { msystem: UCRT64, runner: windows-2022},
          { msystem: CLANG64, runner: windows-2022},
          # { msystem: MINGW64, runner: windows-2022},
          # { msystem: MINGW32, runner: windows-2022},
          # { msystem: CLANGARM64, runner: windows-11-arm}
        ]
    name: ${{ matrix.msystem }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout jank-win at built commit
        run: |
          git clone https://github.com/ikappaki/jank-win.git jank-win
          cd jank-win
          git checkout ${{ needs.windows-build-clang.outputs.jank-win-commit }}
          git submodule update --init --recursive --jobs 8

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: base-devel curl zip mingw-w64-clang-x86_64-git-lfs mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-dlfcn mingw-w64-clang-x86_64-libffi mingw-w64-clang-x86_64-doctest mingw-w64-clang-x86_64-libzip
          update: true

      - name: Cache Clang/LLVM
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: |
            ${{ github.workspace }}/jank-win/compiler+runtime/build/llvm-install
          key: clang-${{ runner.os }}-${{ hashFiles('jank-win/compiler+runtime/bin/build-clang', 'jank-win/compiler+runtime/third-party/MINGW-packages/mingw-w64-llvm/**') }}
      # - name: Download LLVM/Clang
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: clang64-build
      #     path: jank-win/compiler+runtime/build/llvm-install

      - name: install jank clang64 compiler
        shell: msys2 {0}
        run: |
          cd jank-win/compiler+runtime
          ./bin/build-clang -i
          clang++ --version

      - name: build
        shell: msys2 {0}
        run: |
          dos2unix PKGBUILD
          mkdir -p src
          mv jank-win src
          makepkg-mingw -s -f -i -C .
          ls -al

      - name: test
        shell: msys2 {0}
        run: |
          jank check-health
